/*
Navicat MySQL Data Transfer

Source Server         : dbmon
Source Server Version : 50717
Source Host           : 192.168.48.50:3306
Source Database       : db_monitor_dev

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2020-01-19 17:07:50
*/

INSERT INTO `alarm_conf` VALUES (1, 1, 'Oracle', '>=', 1, 'Row number', 'oracle_stat', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleDatabase on and off the alarm \',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name\n             ) content\n  from oracle_stat\n where status = 1\n and %s>0\n and %s', 'oracle_list', 'alarm_connect');
INSERT INTO `alarm_conf` VALUES (2, 1, 'OraclE alarm database table space utilization', '>=', 90, 'Use % ', 'oracle_tablespace', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleThe alarm database table space utilization\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\n Table space name：\',\n              tablespace_name,\n              \'\\n Table space size(GB)：\',\n              total_size,\n              \'\\n Table space utilization：\',\n              percent_used,\n              \'%%\',\n              \'\\n Table space remaining size(GB)：\',\n              free_size) content\n  from oracle_tablespace\n where percent_used >= %s and free_size<1\n  and %s', 'oracle_list', 'alarm_tablespace');
INSERT INTO `alarm_conf` VALUES (4, 1, 'OraclE temporary tablespace alarm database', '>=', 90, 'Use percentage', 'oracle_temp_tablespace', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleThe alarm database temporary table space utilization\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\n Temporary table space name：\',\n              temptablespace_name,\n              \'\\n Temporary table space size(MB)：\',\n              total_size,\n              \'\\n Temporary table space utilization：\',\n              percent_used,\n              \'%%\',\n              \'\\n Temporary table space has been used in size(MB)：\',\n              used_size) content\n  from oracle_temp_tablespace\n where percent_used >= %s and total_size-used_size<1000\n  and %s', 'oracle_list', 'alarm_temp_tablespace');
INSERT INTO `alarm_conf` VALUES (6, 1, 'OraclE database Undo tablespace alarm', '>=', 90, 'Use percentage', 'oracle_undo_tablespace', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleUse database undo tablespace alarm\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\n undoTable space name：\',\n              undotablespace_name,\n              \'\\n undoTable space size(MB)：\',\n              total_size,\n              \'\\n undoTable space utilization：\',\n              percent_used,\n              \'%%\',\n              \'\\n undoTable space has been used in size(MB)：\',\n              used_size) content\n  from oracle_undo_tablespace\n where percent_used >= %s and total_size-used_size<1000\n  and %s', 'oracle_list', 'alarm_undo_tablespace');
INSERT INTO `alarm_conf` VALUES (8, 1, 'OraclE database connection number of the alarm', '>=', 90, 'Use percentage', 'oracle_stat', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OraclE database connection number usage warning\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\nMaximum number of connections：\',\n              max_process,\n              \'\\n The current number of connections：\',\n              current_process,\n              \'\\n The number of connections usage：\',\n              process_used_percent,\n              \'%%\') content\n  from oracle_stat\n where process_used_percent >= %s\n  and %s', 'oracle_list', 'alarm_process');
INSERT INTO `alarm_conf` VALUES (9, 1, 'OraclE adg delay alarm database', '>=', 300, 'unit：seconds', 'oracle_stat', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleADG delay alarm database\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\n ADGTransmission delay：\',\n              adg_trans_value,\n              \'\\n ADGApplication of delay：\',\n              adg_apply_value) content\n  from oracle_stat\n where database_role=\'PHYSICAL STANDBY\' and\n greatest(adg_trans_value,adg_apply_value) >= %s\n  and %s', 'oracle_list', 'alarm_adg');
INSERT INTO `alarm_conf` VALUES (10, 1, 'OraclE background database log alarms', '>=', 1, 'Logging anomaly detection the background', NULL, 'select tags,\r\n       concat(host, \':\', port, \'/\', service_name) url,  \r\n       concat(tags,\r\n              \':OracleBackground database log alarms\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n The databaseurl: \',\r\n              host,\r\n              \':\',\r\n              port,\r\n              \'/\',\r\n              service_name,\r\n              \' \\n Exception information:\',\r\n              err_info\r\n             ) content\r\n  from oracle_db\r\n where err_info is not null\r\n  and 99>%s\r\n  and %s', 'oracle_list', 'alarm_alert_log');
INSERT INTO `alarm_conf` VALUES (11, 1, 'OraclE alarm database comprehensive performance ', '>=', 100, 'Waiting for the number of events per unit time', NULL, 'select tags,\r\n       concat(host, \':\', port, \'/\', service_name) url,\r\n       concat(tags,\r\n              \':OracleComprehensive performance alarm database\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n The databaseurl: \',\r\n              host,\r\n              \':\',\r\n              port,\r\n              \'/\',\r\n              service_name,\r\n              \' \\n Waiting for the event number:\',\r\n              cnt_all) content\r\n  from (select tags, host, port, service_name, sum(event_cnt) cnt_all\r\n          from oracle_db_event_his\r\n         where timestampdiff(minute, chk_time, current_timestamp()) < 30\r\n         group by tags, host, port, service_name) t\r\n where cnt_all >= %d \r\n  and %s', 'oracle_list', 'alarm_wait_events');
INSERT INTO `alarm_conf` VALUES (12, 1, 'OraclE database pga usage warning ', '>=', 90, 'Use percentage', 'oracle_stat', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OraclE PGA usage alarm database\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \' \\n PGAUse the size(MB)：\',\n              pga_used_size,\n              \'\\n PGAusage：\',\n              pga_used_percent,\n              \'%%\') content\n  from oracle_stat\n where pga_used_percent >= %s\n  and %s', 'oracle_list', 'alarm_pga');
INSERT INTO `alarm_conf` VALUES (13, 1, 'OraclE database archive usage warning', '>=', 90, 'Use percentage', 'oracle_stat', 'select tags,\n       concat(host, \':\', port, \'/\', service_name) url,  \n       concat(tags,\n              \':OracleDatabase archive usage warning\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port,\n              \'/\',\n              service_name,\n              \'\\n Archive utilization：\',\n              archive_used_percent ,\n              \'%%\') content\n  from oracle_stat\n where archive_used_percent >= %s\n  and %s', 'oracle_list', 'alarm_archive');
INSERT INTO `alarm_conf` VALUES (14, 1, 'OraclE database lock faults', '>=', 100, 'Locking time，unit：seconds', NULL, 'select tags,\r\n       concat(host, \':\', port, \'/\', service_name) url,  \r\n       concat(tags,\r\n              \':OracleDatabase lock faults\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n The database of url: \',\r\n              host,\r\n              \':\',\r\n              port,\r\n              \'/\',\r\n              service_name,\r\n              \'\\n The sessionSID：\',\r\n              session_id,\r\n              \'\\n Waiting time：\',\r\n              ctime,\r\n              \'(in seconds)\',\r\n              \'\\n The lock type：\',\r\n              type) content\r\n  from oracle_lock\r\n where session like \'Waiter%%\'\r\n and ctime > \'%s\'\r\n  and %s', 'oracle_list', 'alarm_lock');
INSERT INTO `alarm_conf` VALUES (16, 1, 'OraclE failure index alarm', '>=', 1, 'Test failure index', NULL, 'select tags,\r\n       concat(host, \':\', port, \'/\', service_name) url,  \r\n       concat(tags,\r\n              \':OraclE index data failure alarm\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n The database of url: \',\r\n              host,\r\n              \':\',\r\n              port,\r\n              \'/\',\r\n              service_name,\r\n              \'\\n The user name：\',\r\n              owner,\r\n              \'\\n The index name：\',\r\n              index_name,\r\n              \'\\n The name of the partition：\',\r\n              partition_name,\r\n              \'\\n The index state：\',\r\n              status) content\r\n  from oracle_invalid_index\r\n  and 99>%s\r\n  and %s', 'oracle_list', 'alarm_invalid_index');
INSERT INTO `alarm_conf` VALUES (17, 4, 'LinuxThe host on and off the alarm', '>=', 2, 'A row number', 'linux_stat', 'select tags,\n       host url,  \n       concat(tags,\n              \':LinuxThe host on and off the alarm\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n Host IP: \',\n              host\n             ) content\n  from linux_stat\n where status = 1 and 99 > %s\n  and %s', 'linux_list', 'alarm_connect');
INSERT INTO `alarm_conf` VALUES (18, 4, 'LinuxAlarm host CPU utilization', '>=', 90, 'Use percentage', 'linux_stat', 'select tags,\n       host url,\n       concat(tags,\n              \':LinuxAlarm host CPU utilization\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n Host IP: \',\n              host,\n              \'\\n CPUusage：\',\n              cpu_used,\n              \'%%\') content\n  from linux_stat\n where cpu_used >= %s\n  and %s', 'linux_list', 'alarm_cpu');
INSERT INTO `alarm_conf` VALUES (19, 4, 'LinuxAlarm host memory utilization', '>=', 90, 'Use percentage', 'linux_stat', 'select tags,\n       host url,  \n       concat(tags,\n              \':LinuxAlarm host memory utilization\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The hostIP: \',\n              host,\n              \'\\n Memory usage：\',\n              mem_used,\n              \'%%\'\n             ) content\n  from linux_stat\n where mem_used >= %s\n  and %s', 'linux_list', 'alarm_mem');
INSERT INTO `alarm_conf` VALUES (20, 4, 'LinuxThe host file system usage warning', '>=', 95, 'Use percentage', 'linux_disk', 'select tags,\n       host url,  \n       concat(tags,\n              \':LinuxThe host disk usage warning\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The hostIP: \',\n              host,\n              \' \\n Directory name：\',\n              mount_point,\n              \' \\n Directory total size(GB)：\',\n              round(total_size/1024,2),\n              \'\\n Directory available size(GB)\',\n              round(free_size/1024,2),\n              \'\\n usage：\',\n              used_percent,\n              \'%%\'\n             ) content\n  from linux_disk\n where used_percent >= %s\n       and free_size < 5\n  and %s', 'linux_list', 'alarm_disk');
INSERT INTO `alarm_conf` VALUES (21, 2, 'MySQL database on and off the alarm', '>=', 1, 'A row number', 'mysql_stat', 'select tags,\n       concat(host, \':\', port) url,  \n       concat(tags,\n              \':MySQLDatabase on and off the alarm\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n The databaseurl: \',\n              host,\n              \':\',\n              port\n             ) content\n  from mysql_stat\n where status = 1 and 99 > %s\n  and %s', 'mysql_list', 'alarm_connect');
INSERT INTO `alarm_conf` VALUES (23, 4, 'LinuxAlarm host swap utilization', '>=', 10, 'Use percentage', 'linux_stat', 'select tags,\n       host url,  \n       concat(tags,\n              \':LinuxAlarm host SWAP utilization\',\n              \'\\n The alarm time：\',\n              current_timestamp(),\n              \' \\n 主机IP: \',\n              host,\n              \'\\n SWAP utilization：\',\n              round(swap_used*100/(swap_used+swap_free),2),\n              \'%%\'\n             ) content\n  from linux_stat\n where (swap_used+swap_free)>0 and swap_used*100/(swap_used+swap_free) >= %s\n  and %s', 'linux_list', 'alarm_swap');
INSERT INTO `alarm_conf` VALUES (24, 3, 'RediS on and off the alarm', '>=', 1, 'A row number', NULL, 'select tags,\r\n       concat(host, \':\', port) url,  \r\n       concat(tags,\r\n              \':RedisOn and off the alarm\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n Redis url: \',\r\n              host,\r\n              \':\',\r\n              port\r\n             ) content\r\n  from redis\r\n where mon_status = \'connected error\' and 99 > %s\r\n  and %s', 'redis_list', 'alarm_connect');
INSERT INTO `alarm_conf` VALUES (25, 3, 'RedisMemory usage warning', '>=', 80, 'Use percentage', NULL, 'select tags,\r\n       concat(host, \':\', port) url,  \r\n       concat(tags,\r\n              \':RedisMemory usage warning\',\r\n              \'\\n The alarm time：\',\r\n              current_timestamp(),\r\n              \' \\n Redis url: \',\r\n              host,\r\n              \':\',\r\n              port,\r\n              \' \\n Maximum memory configuration(MB)\',\r\n              max_memory,\r\n              \' \\n The use of memory size(MB)\',\r\n              used_memory,\r\n              \' \\n Memory usage\',\r\n              used_memory_pct,\r\n              \'%%\'\r\n             ) content\r\n  from redis\r\n where used_memory_pct >= %s\r\n  and %s', 'redis_list', 'alarm_mem');

INSERT INTO `django_celery_beat_intervalschedule` VALUES ('1', '1', 'minutes');

INSERT INTO `django_celery_beat_intervalschedule` VALUES ('2', '10', 'minutes');

INSERT INTO `django_celery_beat_intervalschedule` VALUES ('3', '30', 'minutes');


INSERT INTO `django_celery_beat_periodictask` VALUES ('3', 'maincheck', 'system.tasks.main_check', '[]', '{}', null, null, null, null, '1', now(), '0', now(), '', null, '1', null, '0', null, null, '{}', null);

INSERT INTO `users` VALUES ('1', 'pbkdf2_sha256$150000$Ky2xUHG0UsAf$pLW6ZiA45dekRVmBVUOt/fCkwb9ovbTicoTePh8S2i4=', '2020-05-20 10:40:37.840189', '1', 'admin', '', '', '', '1', '1', '2020-05-20 10:38:48.529826', null, null, null);
